name = "HokseonAssistant"
uuid = "4e992a72-38bf-4f56-b165-33bbf4775b47"
authors = ["Hokseon Lou <louhokseson@outlook.com>"]
version = "1.2.3"

[deps]
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
ClusterManagers = "2.0.0"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
